server:
  port: 8072
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance: 
    preferIpAddress: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
            routes:
              - id: license-service
                predicates:
                  - Path=/licsvc/**
                uri: lb://LICENSE-SERVICE
                filters:
                  - RewritePath=/licsvc/(?<segment>.*), /$\{segment}
              - id: organization-service
                predicates:
                  - Path=/orgsvc/**
                uri: lb://ORGANIZATION-SERVICE
                filters:
                  - RewritePath=/orgsvc/(?<segment>.*), /v1/${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted              