management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
        exclude:
          - beans
  endpoint:
    health:
      show-details: always			
  health:
    diskspace:
      enabled: true
server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: "{cipher}f4acf57c5b97d82cd7b54a7fe066d0145a0b0b54793622a985ccdc99458a2a41"
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance: 
    preferIpAddress: true
